// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBacqmE_SHvXIHOp9zQAmmmLAtUSZqy_ys',
    appId: '1:760835345024:web:670b2b8804e9384a23f465',
    messagingSenderId: '760835345024',
    projectId: 'my-balancebox-ub',
    authDomain: 'my-balancebox-ub.firebaseapp.com',
    storageBucket: 'my-balancebox-ub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CMMOyJs5XMfeoPsL8W8aq9ebZERic1U',
    appId: '1:760835345024:android:23ee4be722cddccd23f465',
    messagingSenderId: '760835345024',
    projectId: 'my-balancebox-ub',
    storageBucket: 'my-balancebox-ub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu8xuGFw8qXqoiijcuSm1QfXAjvzZd8fI',
    appId: '1:760835345024:ios:0511929eeb1126de23f465',
    messagingSenderId: '760835345024',
    projectId: 'my-balancebox-ub',
    storageBucket: 'my-balancebox-ub.firebasestorage.app',
    iosBundleId: 'ub.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu8xuGFw8qXqoiijcuSm1QfXAjvzZd8fI',
    appId: '1:760835345024:ios:0511929eeb1126de23f465',
    messagingSenderId: '760835345024',
    projectId: 'my-balancebox-ub',
    storageBucket: 'my-balancebox-ub.firebasestorage.app',
    iosBundleId: 'ub.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBacqmE_SHvXIHOp9zQAmmmLAtUSZqy_ys',
    appId: '1:760835345024:web:7e2fc385937617aa23f465',
    messagingSenderId: '760835345024',
    projectId: 'my-balancebox-ub',
    authDomain: 'my-balancebox-ub.firebaseapp.com',
    storageBucket: 'my-balancebox-ub.firebasestorage.app',
  );

}